# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/yu5866da-s/vivado/project_2/project_2.cache/wt [current_project]
set_property parent.project_path C:/Users/yu5866da-s/vivado/project_2/project_2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/yu5866da-s/vivado/project_2/project_2.srcs/sources_1/new/counter.vhd
  C:/Users/yu5866da-s/vivado/project_2/project_2.srcs/sources_1/imports/Lab2/edge_detector.vhd
  C:/Users/yu5866da-s/vivado/project_2/project_2.srcs/sources_1/imports/Lab2/convert_scancode.vhd
  C:/Users/yu5866da-s/vivado/project_2/project_2.srcs/sources_1/imports/Lab2/keyboard_ctrl.vhd
  C:/Users/yu5866da-s/vivado/project_2/project_2.srcs/sources_1/imports/Lab2/sync_keyboard.vhd
  C:/Users/yu5866da-s/vivado/project_2/project_2.srcs/sources_1/imports/Lab2/binary_to_sg.vhd
  C:/Users/yu5866da-s/vivado/project_2/project_2.srcs/sources_1/imports/Lab2/convert_to_binary.vhd
  C:/Users/yu5866da-s/vivado/project_2/project_2.srcs/sources_1/imports/Lab2/keyboard_top.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top keyboard_top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef keyboard_top.dcp

catch { report_utilization -file keyboard_top_utilization_synth.rpt -pb keyboard_top_utilization_synth.pb }
