# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/yu5866da-s/vivado/lab0/lab0.cache/wt [current_project]
set_property parent.project_path C:/Users/yu5866da-s/vivado/lab0/lab0.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib C:/Users/yu5866da-s/vivado/lab0/lab0.srcs/sources_1/new/lab0.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/yu5866da-s/vivado/lab0/lab0.srcs/constrs_1/new/const.xdc
set_property used_in_implementation false [get_files C:/Users/yu5866da-s/vivado/lab0/lab0.srcs/constrs_1/new/const.xdc]


synth_design -top my_counter -part xc7a100tcsg324-1


write_checkpoint -force -noxdef my_counter.dcp

catch { report_utilization -file my_counter_utilization_synth.rpt -pb my_counter_utilization_synth.pb }
